Added Fir filter module
jhu-cisst/mechatronics-firmware pull request #12
Opened 2021-05-18 18:16 UTC by jtzhangLogan

Removed `FIR` directory, `demo_tb` directory, `FIR.sym` symbol file, `create_FIR.tcl` , and log files generated during ipcore compilation. Maintained `coregen.cgp` and `coregen.cgc` from V.7.0 firmware release.

2021-05-18 21:15 UTC, pkazanzides requested changes
This implementation does not seem correct. I would have expected either 8 FIR filters (4 pot + 4 current) or perhaps a multi-channel design with fewer filters (say, 2).  In the latter case, there needs to be a way to sequence the different channels through the filter.

2021-05-18 21:15 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/FPGA1394Eth-QLA.v
> +assign raw_pot_data = pot_fb[reg_raddr[7:4]];
It seems that there is just one FIR filter for the pot and another FIR filter for the current, but somehow these filters are shared for all 4 channels.  I do not see how the data for each channel is kept separate.  I do not see how reg_raddr[7:4] would be useful here.  It could have any value -- it is based on the last read command that was sent via Ethernet or Firewire.

2021-05-18 21:15 UTC, pkazanzides commented on FPGA1394_QLA/ipcore_dir/FIR.xco
> +CSET coefficientvector=0.014308,0.017565,0.02092,0.024275,0.027728,0.030985,0.034241,0.037201,0.039964,0.042431,0.044504,0.046181,0.047365,0.048155,0.048352,0.048155,0.047365,0.046181,0.044504,0.0424
The coefficient vector is hard-coded.  Is it possible to reconfigure this, for example by downloading new values?  I believe you have 29 coefficients which, although shown as floating point values here, are eventually converted to 16-bit coefficients.  So, we could do a block write of coefficients.  I see above a `CSET coefficient_reload=false`, so probably that would need to be changed. What else would be needed?

2021-07-15 06:40 UTC, jtzhangLogan commented
FIR (pot/cur) enable/disable & coefficient reload functionality have been tested. Expecting further validation...

2021-12-26 05:44 UTC, closed without merging