proceed to state 13, family code wrong
jhu-cisst/mechatronics-firmware pull request #13
Opened 2021-06-02 08:08 UTC by qiguaiderenmen

Error messages:

DS2480B status = 16ffe09b
DS2480B state = 13
Unknown device family code: 0x16 (DS2505 should be 0x0B)

2021-06-03 03:46 UTC, qiguaiderenmen commented
A new update: adding a read state after sending 0x33 (Read ROM Command) solves the issue. Now the error message becomes:

DS2480B status = bffe0db
DS2480B state = 13
Failed to read instrument memory

2021-06-04 22:25 UTC, qiguaiderenmen commented
Update: change several states and now proceed to write data to .txt file. Unfortunately, we only receive 0xFF for all the data.

2021-06-08 00:47 UTC, qiguaiderenmen commented
Update: code refactored with fewer states, 'processor' based functional blocks and more fluent logic flow. More comments involved. Still within all 0xFF data issue, perhaps due to no proper 1-wire configuration involved.

2021-06-09 13:31 UTC, pkazanzides requested changes
This is looking better.  One major issue is that I believe you have broken the direct 1-wire interface.  Making sure that still works is a requirement before merging into the devel branch.

I think the best next step is to completely separate the states related to the direct 1-wire interface and the DS2480B interface. Note also my comment about naming of your states. Using 1_WIRE for states related to the DS2480B (and not the direct 1-wire interface) is extremely confusing. 

Then, make sure the direct 1-wire interface still works.  At the end, we could consider consolidating states between the DS2480B and direct 1-wire interface, as Shi Xin had done to some extent, though I'm not sure it would give much benefit.

Another minor point is that you can also add `DS_RESET_1_WIRE`, `DS_RESP_1_WIRE`, and `DS_SET_DATA_MODE` to the program.  The only "special cases" are the setting of `DS480B_ok` and `ds_reset`, which could be handled differently.  The simplest (though perhaps not best) solution is to set them based on the value of `progCnt`.

I am also thinking that eventually the `DS_RUN_READ_PREP_FUNC_BLK` and `DS_CHECK_BYTE_READ_PREP` could be combined with the "config" states, but that can wait.

2021-06-09 13:31 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +    ds_program[7] = { mem_addr[7:0], mem_addr[7:0] };    // DS_SET_ADDR_LOW, DS_RESP_ADDR_LOW
I am not sure this will work as intended.  Does it just initialize ds_program[7:8] with the current contents of mem_addr (presumably 0)?

2021-06-09 13:31 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +       tx_data <= {1'b1, 8'hE3, 1'b0};
Why was this state changed?  It is only used for the direct 1-wire interface, which it seems you have broken.

2021-06-09 13:31 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +             // previously here's DS_READ_PROM_START, maybe need to recover in the future
Same issue.  You are breaking the direct 1-wire interface

2021-06-09 13:31 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +    DS_WAIT_2MS_1_WIRE  = 9,
Your state names are confusing.  You are using 1_WIRE for states that are used with the DS2480B chip.  Note that the alternative (current working implementation) is the direct 1-wire interface, so this could lead to some confusion.  Perhaps it would be better to use DS2480B instead of 1_WIRE.

2021-06-09 13:31 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +          unexpected_idx <= 1;  // optiional for debugging, start with 1 since 0 will skip read check
This line not needed.  `unexpected_idx` will be set in the next state.

2021-06-09 13:31 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +          mem_data[num_bytes[7:2]] <= (mem_data[num_bytes[7:2]] << 8) | in_byte;
I'm not sure this will update `ds_program`.  Instead of updating `mem_data`, you could directly update `ds_program[7:8]`

2021-06-09 13:31 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +          unexpected_idx <= 1;  // optiional for debugging, start with 1 since 0 will skip read check
More importantly, you should set `progCnt` rather than assuming it will be 5, because once the DS2480B is configured, future calls will jump directly to `DS_RESET_1_WIRE` and in that case `progCnt` will probably not be 5.

2021-06-11 02:23 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +    ds_program[7] = { mem_addr[7:0], mem_addr[7:0] };    // DS_SET_ADDR_LOW, DS_RESP_ADDR_LOW
Yes professor, I've changed the statements from 'initial' to 'assign'.

2021-06-11 02:24 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +       tx_data <= {1'b1, 8'hE3, 1'b0};
These parts are just ignored for now, will merge them once the ds2480 functionality is ready.

2021-06-11 02:26 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +             // previously here's DS_READ_PROM_START, maybe need to recover in the future
Yeah, same to previous one.

2021-06-11 02:27 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +    DS_WAIT_2MS_1_WIRE  = 9,
Thanks for pointing out! The name has been changed to DS_WAIT_2MS_FOR_2480_RESET, as well as other 2ms delay states.

2021-06-11 02:31 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +          unexpected_idx <= 1;  // optiional for debugging, start with 1 since 0 will skip read check
Yeah that's a huge bug! `progCnt` is now assigned to 5 and the program looks much more solid.

2021-06-11 02:36 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +          mem_data[num_bytes[7:2]] <= (mem_data[num_bytes[7:2]] << 8) | in_byte;
No professor, this part has no relationship to `ds_program`, from my perspective. It is continuously sending 0xFF and storing the received bytes to mem_data (in the most recent update I reduce the number to 8 bytes, but still get all ff). If you mean mem_addr, I think it's updated in the very beginning of DS_IDLE state.

2021-06-11 03:15 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +          mem_data[num_bytes[7:2]] <= (mem_data[num_bytes[7:2]] << 8) | in_byte;
Right. I had confused mem_data with mem_addr.

2021-06-11 03:16 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +initial DS2480B_ok <= 1'b1;
I assume this is temporary. You should not be initializing to 1.

2021-06-12 08:01 UTC, qiguaiderenmen commented
In commit ee4fd44, Jie Ying's 5 original files are included (to distinguish from current serial code they're modified to ds_<name>).
In commit cc6b4b9, some modifications are made, but we can't read anything from the chip. Maybe due to wrong settings in FPGA1394Eth-QLA.v, not pretty sure.

2021-07-05 05:37 UTC, qiguaiderenmen commented
Works! I've replaced the fragile Read state with my own receive implementation. It works just fine and I'll do some code refine & adjustment with direct wire interface.

2021-07-10 01:22 UTC, qiguaiderenmen commented
Commit `f382161` is the working version with old serial write implementation, commit `6895d22` is in new style but doesn't work.

2021-07-14 22:52 UTC, qiguaiderenmen commented
Serial trial for both old / new QLA & 1-wire trial for new QLA have been tested and validated. Everything works just fine.

2021-08-09 03:40 UTC, pkazanzides requested changes
Please clean up the serial port code. I see some serial port code in DS2505.v and then there are files uart_recv_2480.v and uart_send_2480.v.  Please delete the code that is not being used.  Also, change tabs to spaces.

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/uart_recv_2480.v
> +             case (rx_cnt)
Why not replace this case statement by `rxdata[rx_cnt-1] <= uart_rxd_d1`?

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/uart_recv_2480.v
> +		     rxdata <= rxdata;
Not needed.

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/uart_recv_2480.v
> +module  uart_recv_2480(
Replace tabs by spaces in this file.

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/CMakeLists.txt
> +                           "${VERILOG_SOURCE_DIR}/uart_recv_2480.v"
I see there is also a uart_send_2480.v.  Should that be added to CMakeLists.txt?

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +       family_code <= 8'h0B;                           // assign family code directly, maybe check in the future
This should not be hard-coded.

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +//                       main  code
Why is there uart code here too?

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +wire[15:0]  ds_program[0:8];         // Program arguments
Could add an extra 2 bits and eliminate `DS_CHECK_PROGRAMMER`.  The simplest is to add 5 bits for the next state, but there really are only 3 possible next states, so 2 bits would be enough.

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +reg[9:0]    tx_data;                 // Transmit byte -- needs to be 10 bits -- could be merged with out_byte later
Change this to `wire`. Then, `assign tx_data[9] = 1; assign tx_data[8:1] = out_byte; assign tx_data[0] = 0;`

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +       tx_data <= {1'b1, 8'h00, 1'b0};
Could change to `out_byte <= 8'h00;` (assuming change to `tx_data` described above)

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +       tx_data <= {1'b1, ds_program[progCnt][15:8], 1'b0};
As above, change from `tx_data` to `out_byte`

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +       next_state <= DS_CHECK_PROGRAMMER;
Could do something like `next_state <= next_state_array[ds_program[progCnt][17:16]];`, assuming `next_state_array` is properly set up to specify `DS_PROGRAMMER`, `DS_READ_MEM_REQUEST` or `DS_IDLE`.  Might also needs to set `num_bytes <= 8'd0` here.  Then, can eliminate `DS_CHECK_PROGRAMMER`.

2021-08-09 03:40 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +       tx_data <= {1'b1, 8'hFF, 1'b0};
Again, use `out_byte`.

2021-08-09 13:33 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/uart_recv_2480.v
> +             case (rx_cnt)
Even better, based on what I think you are doing, would be a right shift, where the new data comes in on the left:  `rxdata <= { uart_rxd_d1, rxdata[6:0] };` (that is just one implementation).  You'll have to tweak the code a little to properly handle `rxcnt == 0`, which I think currently does nothing.

2021-08-14 03:59 UTC, pkazanzides approved these changes
A few things left to do, such as reading the family code, but this is good enough to merge now.

2021-08-14 04:10 UTC, merged