Code refine for DS2480B.
jhu-cisst/mechatronics-firmware pull request #18
Opened 2021-08-17 01:17 UTC by qiguaiderenmen

TODO: edit programmer code (done), involve family code reading, test modified software.

2021-08-20 03:43 UTC, pkazanzides requested changes
Looks good, but a few more comments.

2021-08-20 03:43 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +            //  if (progCnt == 4'd3) begin
Can this commented out code be deleted?

2021-08-20 03:43 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +       state <= ds_program[(progCnt-1)][25:21];
This is fine, but can you increment `progCnt` in this state, rather than in `DS_PROGRAMMER`?  That would eliminate the need to subtract 1.  You have one use of `progCnt` in `DS_READ_BYTE` that would have to be updated.

2021-08-20 03:43 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
>            // Inerface auto-detect implementation. For DS2480B serial interface, the
Typo on this line (Inerface should be Interface)

2021-08-20 03:43 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +//         DS_PROGRAMMER      : (1) If current state is DS_PROGRAMMER, indicating
It seems like you have 4 cases here, which could be done with 2 bits rather than 10, but first, I am wondering why `DS_READ_MEM_REQUEST` is a separate state.  Couldn't it be one program line, with bits 15:8 set to 0xff?  You would have to change the code in `DS_IDLE` to set `progCnt` and jump to `DS_PROGRAMMER` instead of `DS_READ_MEM_REQUEST`.

2021-08-25 02:40 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +       state <= ds_program[(progCnt-1)][25:21];
Yeah I'm planning to do that in next revision.

2021-08-25 03:34 UTC, qiguaiderenmen commented on FPGA1394_QLA/Verilog/DS2505.v
> +//         DS_PROGRAMMER      : (1) If current state is DS_PROGRAMMER, indicating
In that case, we'll have problems. Programmer counter in DS_CHECK_PORGRAMMER is always adding 1 in this state. Thus, to latch progCnt until reading end, if-else statement needs to be added in DS_CHECK_PROGRAMMER, which may lead to confusion about the code. What else, we may only use num_bytes to make decision, but it's muxed by both family code read & mem read.

2021-08-25 03:49 UTC, pkazanzides commented on FPGA1394_QLA/Verilog/DS2505.v
> +//         DS_PROGRAMMER      : (1) If current state is DS_PROGRAMMER, indicating
Right. I missed the fact that it is looping for 256 times.

2021-08-26 00:57 UTC, merged